import os
import time
from typing import List, Any, Tuple, Set

import random

from fuzzer.fuzzer import Fuzzer
from runner.runner import Runner
from utils.coverage import Location
from utils.mutator import Mutator
from runner.function_coverage_runner import FunctionCoverageRunner
from schedule.power_schedule import PowerSchedule
from utils.object_utils import dump_object

from utils.seed import Seed

# 持久化配置
PERSIST_INTERVAL = 30          # 每 30 秒持久化一次
PERSIST_DIR = "_persist"       # 中间结果持久化目录
MAX_POPULATION_MEMORY = 500    # 内存中保留的最大种子数


class GreyBoxFuzzer(Fuzzer):

    def __init__(self, seeds: List[str], schedule: PowerSchedule, is_print: bool,
                 persist_dir: str = PERSIST_DIR) -> None:
        """Constructor.
        `seeds` - a list of (input) strings to mutate.
        `mutator` - the mutator to apply.
        `schedule` - the power schedule to apply.
        `persist_dir` - directory for intermediate result persistence.
        """
        super().__init__()
        self.is_print = is_print
        self.last_crash_time = self.start_time
        self.population = []
        self.file_map = {}
        self.covered_line: Set[Location] = set()
        self.seed_index = 0
        self.crash_map = dict()
        self.seeds = seeds
        self.mutator = Mutator()
        self.schedule = schedule
        self.persist_dir = persist_dir
        self._last_persist_time = self.start_time
        self._persist_count = 0
        if is_print:
            print("""
┌───────────────────────┬───────────────────────┬───────────────────┬────────────────┬───────────────────┐
│        Run Time       │    Last Uniq Crash    │    Total Execs    │  Uniq Crashes  │   Covered Lines   │
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤""")


    def create_candidate(self) -> str:
        """Returns an input generated by fuzzing a seed in the population"""
        seed = self.schedule.choose(self.population)

        # Stacking: Apply multiple mutations to generate the candidate
        candidate = seed.data
        trials = min(len(candidate), 1 << random.randint(1, 5))
        for i in range(trials):
            candidate = self.mutator.mutate(candidate)
        return candidate

    def fuzz(self) -> str:
        """Returns first each seed once and then generates new inputs"""
        if self.seed_index < len(self.seeds):
            # Still seeding
            self.inp = self.seeds[self.seed_index]
            self.seed_index += 1
        else:
            # Mutating
            self.inp = self.create_candidate()

        return self.inp

    def print_stats(self):
        if not self.is_print:
            return

        def format_seconds(seconds):
            hours = int(seconds) // 3600
            minutes = int(seconds % 3600) // 60
            remaining_seconds = int(seconds) % 60
            return f"{hours:02d}:{minutes:02d}:{remaining_seconds:02d}"

        template = """│{runtime}│{crash_time}│{total_exec}│{uniq_crash}│{covered_line}│
├───────────────────────┼───────────────────────┼───────────────────┼────────────────┼───────────────────┤"""

        template = template.format(runtime=format_seconds(time.time() - self.start_time).center(23),
                                   crash_time=format_seconds(self.last_crash_time - self.start_time).center(23),
                                   total_exec=str(self.total_execs).center(19),
                                   uniq_crash=str(len(set(self.crash_map.values()))).center(16),
                                   covered_line=str(len(self.covered_line)).center(19))
        print(template)

    def run(self, runner: FunctionCoverageRunner) -> Tuple[Any, str]:  # type: ignore
        """Run function(inp) while tracking coverage.
           If we reach new coverage,
           add inp to population and its coverage to population_coverage
        """
        result, outcome = super().run(runner)
        if len(self.covered_line) != len(runner.all_coverage):
            self.covered_line |= runner.all_coverage
            if outcome == Runner.PASS:
                # We have new coverage
                seed = self._make_seed(runner)
                self.population.append(seed)
        if outcome == Runner.FAIL:
            self.last_crash_time = time.time()
            self.crash_map[self.inp] = result

        # 周期性持久化 & 内存控制
        self._maybe_persist()

        return result, outcome

    def _make_seed(self, runner: FunctionCoverageRunner) -> Seed:
        """Create a Seed from the current input and runner state.
        Subclasses may override to attach extra attributes (e.g. path_key).
        """
        return Seed(self.inp, runner.coverage())

    def _maybe_persist(self) -> None:
        """每隔 PERSIST_INTERVAL 秒将 population 和 crash_map 持久化到磁盘，
        并将超出 MAX_POPULATION_MEMORY 的低能量种子从内存中移除。"""
        now = time.time()
        if now - self._last_persist_time < PERSIST_INTERVAL:
            return

        self._last_persist_time = now
        self._persist_count += 1

        # 持久化 population 快照
        dump_object(os.path.join(self.persist_dir, "population.pkl"), self.population)

        # 持久化 crash_map 快照
        if self.crash_map:
            dump_object(os.path.join(self.persist_dir, "crash_map.pkl"), self.crash_map)

        # 持久化覆盖率集合
        dump_object(os.path.join(self.persist_dir, "covered_line.pkl"), self.covered_line)

        # 内存控制：population 超过阈值时，淘汰能量最低的种子
        if len(self.population) > MAX_POPULATION_MEMORY:
            # 先触发一次 energy 计算
            self.schedule.assign_energy(self.population)
            # 按能量排序，保留前 MAX_POPULATION_MEMORY 个
            self.population.sort(key=lambda s: s.energy, reverse=True)
            self.population = self.population[:MAX_POPULATION_MEMORY]
